language: node_js

node_js: 6.0.0

install:
  - npm install acyort -g

script:
  - acyort clean
  - acyort init
  - cp config.bak.yml config.yml
  - rm config.bak.yml
  - git clone https://github.com/acyortjs/theme-donob.git themes/donob
  - acyort build

after_script:
  - git add .
  - git config user.name "LoeiFy"
  - git config user.email "LoeiFy@gmail.com"
  - git commit -m "update from travis-ci"
  - git push https://${GH_TOKEN}@github.com/acyortjs/acyortjs.github.io.git master:master