title: AcyOrt
keywords: website,acyort,static
description: A Node.js static website framework

template: pavane

menu:
  docs: /docs/
  api: /api/
  miscellaneous: /miscellaneous/

plugins:
  - script.js
  - acyort-toc
  - acyort-server

public: docs

timezone: Asia/Shanghai

languages:
  en: English
  zh_CN: 简体中文
