title: AcyOrt
keywords: website,acyort,static
description: A Node.js static website framework

template: pavane

menu:
  docs: /docs/
  api: /api/
  miscellaneous: /miscellaneous/

plugins:
  - script.js
  - acyort-toc
  - acyort-server

public: docs

timezone: Asia/Shanghai

languages:
  en: English
  zh_cn: 简体中文

docs_nav:
  Getting Started:
    - Overview
    - Setup
    - Configuration
    - Command
  Customization:
    - Template
    - Plugin
    - Helper

api_nav:
  API:
    - Overview
    - Renderer
    - Cli
    - Store
    - Workflow
    - Helper
    - Util
    - Hooks
