title: AcyOrt
keywords: website,acyort,static
description: A Node.js static website framework

template: pavane

menu:
  docs: /docs/
  api: /api/
  miscellaneous: /miscellaneous/

plugins:
  - script.js
  - acyort-toc
  - acyort-server

public: docs

timezone: Asia/Shanghai

language: en

languages:
  zh-cn: 简体中文

docs_nav:
  Getting Started:
    - Overview
    - Setup
    - Configuration
    - Command
  Customization:
    - Template
    - Variable
    - Helper
    - Plugin

api_nav:
  API:
    - Overview
    - Method
    - Store
    - Process
    - CLi
    - Workflow
    - Helper
    - Output
