title: AcyOrt
keywords: website,acyort,static
description: A Node.js static website framework

template: pavane

menu:
  docs: /docs/
  api: /api/
  miscellaneous: /miscellaneous/

plugins:
  - script.js
  - acyort-toc
  - acyort-server

public: docs

timezone: Asia/Shanghai

language: en

languages:
  zh-cn: 简体中文
