
# site
title: AcyOrt
description: A Node.js blog tool powered by GitHub. 
keywords: acyort, nodejs, blog
rss: rss.xml
favicon: /icon.png

# site url. you can set as 'http://yoursite.com/child' if need
# please add 'http://' or 'https://'
url: http://acyort.github.io

# site permalink
# id, time or category
# e.g.
# id: 'posts/id.html'
# time: 'year/month/id.html'
# category: 'category_dir/category_name/id.html'
permalink: id

# comment
comment:
    disqus: acyort
    duoshuo:

# theme
theme: donob

# pagination
per_page: 20
archives_per_page: 30

#menu
menu:
    home: /
    about: /
    archives: /

# category
default_category: uncategorized

# html output directory or child directory e.g. 'child'
public_dir: /

# category directory
category_dir:

# tag directory
tag_dir:

# site content issue
# username/repository
issue_repo: lifesinger/blog

# thumbnail mode 
# 1: use the first image as thumbnail and remove the image
# 2: use the first image as thumbnail but not remove the image
thumbnail_mode: 2

# thumbnail size
# whether to get the thumbnail size
thumbnail_size: false

# site post authors filter
authors:
#    - LoeiFy
#    - author0
#    - author1

# GitHub access token(Optional)
# token should be separated by whitespace if you push this file to GitHub 
# token: sd46a6d65a asd8sdbn

# dev mode
# boolean / string
# you can set test json path: test/test.json 
dev: false
