title: AcyOrt
description: A Node.js static website framework. Powered by GitHub.

url: https://acyort.com
theme: Pavane

menu:
  docs: /docs/
  api: /api/
  deploy: /deploy/
  development: /development/
  troubleshooting: /troubleshooting/

user: acyortjs
repository: site

scripts:
  - nav.js
  - category.js
  - template.js
  - min.js
  - updated.js
  - i18n.js
plugins:
  - acyort-toc

public_dir: public

authors:
  - LoeiFy

timezone: Asia/Shanghai
line_numbers: false
order: updated

token: 5#c21bffc137f44faf7e9c4a84da827f7cc2cfeaa

cache: true

keywords: website,blog,github,static,issues

languages:
  zh-cn: 简体中文

docs_nav:
  Getting Started:
    - Overview
    - Setup
    - Configuration
  Basic Usage:
    - Writing
    - Commands
  Customization:
    - Permalink
    - Themes
    - Variables
    - Helpers
    - Plugins

api_nav:
  API:
    - Overview
    - Filter
    - Methods
