title: AcyOrt
keywords: website,acyort,github,static,issues
description: A Node.js static website framework

url: https://acyort.com
template: pavane

menu:
  docs: /docs/
  api: /api/
  development: /development/


repository: acyortjs/site

scripts:
  - script.js

plugins:
  - acyort-toc
  - acyort-server

public: public

authors:
  - LoeiFy

timezone: Asia/Shanghai

language: en

languages:
  zh-cn: 简体中文

docs_nav:
  Getting Started:
    - Overview
    - Setup
    - Configuration
  Basic Usage:
    - Commands
  Customization:
    - Templates
    - Variables
    - Helpers
    - Plugins

api_nav:
  API:
    - Overview
    - Methods
