version: 2
jobs:
  build:
    docker:
      - image: node:latest

    working_directory: ~/acyort

    branches:
      ignore:
        - gh-pages
      only:
        - master

    steps:
      - checkout
      - run: npm install acyort -g
      - run: acyort init
      - run: npm i
      - run: acyort flow
      - run: git checkout .
      - run: git checkout gh-pages
      - run: git reset --hard origin/gh-pages
      - run: cp -R public/* .
      - run: rm -R public
      - run: git add .
      - run: git config user.name "LoeiFy"
      - run: git config user.email "LoeiFy@gmail.com"
      - run: git commit -m "Updated by circleci - `date`"
      - run: git push -q https://${gh_token}@github.com/acyortjs/site.git gh-pages:gh-pages
