version: 2
jobs:
  build:
    docker:
      - image: node:latest

    working_directory: ~/acyort

    branches:
      only:
        - master

    steps:
      - checkout
      - run: npm install acyort -g
      - run: npm i
      - run: acyort clean
      - run: acyort flow
      - run: git add .
      - run: git config user.name "LoeiFy"
      - run: git config user.email "LoeiFy@gmail.com"
      - run: git commit -m "Updated by circleci - `date` [ci skip]" # 一定要添加 [ci skip]，不然会死循环构建
      - run: git push -q https://${gh_token}@github.com/acyortjs/site.git master:master
